# PostgreSQL configuration for Docker environment
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  timeout: 5000
  # PostgreSQL Prepared Statement問題を防ぐための設定
  prepared_statements: false

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'portfolio_development' %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: portfolio_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: portfolio_production
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  sslmode: require
  statement_limit: 0
  advisory_locks: false

  pool: 3
  connect_timeout: 30
  checkout_timeout: 5
  idle_timeout: 60
  reaping_frequency: 10
  reconnect: true

  # The password associated with the PostgreSQL role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
