services:
  db:
    image: postgres:15
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio_development
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    volumes:
      - ./backend:/rails # WORKDIRに合わせる
      # - backend_bundle:/usr/local/bundle # 開発環境では各コンテナが独自のGemをインストールできるようにする
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/portfolio_development
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "0"
      BUNDLE_WITHOUT: ""
    tty: true
    stdin_open: true
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api/v1
    tty: true
    stdin_open: true
    command: npm run dev

volumes:
  postgres_data:
  backend_bundle:
  frontend_node_modules:
