require:
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/*'
    - 'config/initializers/devise.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/controllers/api/v1/payment_intents_controller.rb'
    - 'app/controllers/api/v1/webhooks_controller.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/controllers/api/v1/payment_intents_controller.rb'
    - 'app/controllers/api/v1/webhooks_controller.rb'

# FactoryBot cops (新しい命名規則)
FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

FactoryBot/FactoryNameStyle:
  Enabled: true

FactoryBot/SyntaxMethods:
  Enabled: true

# Capybara cops (新しい命名規則)
Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Capybara/VisibilityMatcher:
  Enabled: true

# RSpecRails cops (新しい命名規則)
RSpecRails/AvoidSetupHook:
  Enabled: true

RSpecRails/HaveHttpStatus:
  Enabled: true

RSpecRails/HttpStatus:
  Enabled: true

RSpecRails/InferredSpecType:
  Enabled: true

RSpecRails/MinitestAssertions:
  Enabled: true

RSpecRails/NegationBeValid:
  Enabled: true

RSpecRails/TravelAround:
  Enabled: true
