require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/*'
    - 'config/initializers/devise.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/controllers/api/v1/payment_intents_controller.rb'
    - 'app/controllers/api/v1/webhooks_controller.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/controllers/api/v1/payment_intents_controller.rb'
    - 'app/controllers/api/v1/webhooks_controller.rb'
