FROM ruby:3.2.2-slim

# 開発環境用の依存パッケージをインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    git \
    pkg-config \
    zlib1g-dev \
    curl \
    libvips \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Rails アプリケーションディレクトリを作成
WORKDIR /rails

# 環境変数を設定
ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

# Gemfileをコピーして依存関係をインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションコードをコピー
COPY . .

# サーバー起動
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
